name: Terraform EC2 Provisioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Delete existing security group (if it exists)
      - name: Delete existing security group (if it exists)
        run: |
          SG_ID=$(aws ec2 describe-security-groups --filters Name=group-name,Values=allow_http --query "SecurityGroups[0].GroupId" --output text)
          if [ "$SG_ID" != "None" ]; then
            aws ec2 delete-security-group --group-id $SG_ID
            echo "Deleted existing security group: $SG_ID"
          else
            echo "No existing security group found"
          fi

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Run Terraform Plan
      - name: Run Terraform Plan
        run: terraform plan

      # Step 6: Run Terraform Apply
      - name: Run Terraform Apply
        run: terraform apply -auto-approve

      # Step 7: Output EC2 Public IP
      - name: Output EC2 Public IP
        run: echo "EC2 Public IP: $(terraform output -raw instance_public_ip)"

      - name: Run Terraform Apply
        run: terraform apply -auto-approve


