name: Terraform EC2 Provisioning

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Plan Terraform
      - name: Terraform Plan
        run: terraform plan

      # Step 5: Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 6: Output EC2 Public IP (This is the step you're having issues with)
      - name: Output EC2 IP
        run: |
          echo "EC2 Public IP: $(terraform output -raw instance_public_ip)"


