name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./terraform  # Specify the directory containing the Terraform files
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform  # Specify the directory containing the Terraform files
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform  # Specify the directory containing the Terraform files
        run: terraform apply -auto-approve

      - name: Output EC2 IP
        working-directory: ./terraform  # Specify the directory containing the Terraform files
        run: echo "EC2 Public IP: $(terraform output -raw ec2_public_ip)"


